// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDzQjyyRe4LKJGqeR7OBHgXc3uPgWBsxQ',
    appId: '1:394923376722:web:46a8428253b774160a5f8b',
    messagingSenderId: '394923376722',
    projectId: 'fir-authentication-752b6',
    authDomain: 'fir-authentication-752b6.firebaseapp.com',
    storageBucket: 'fir-authentication-752b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IyC7DPaQjhcC2WHSwWDx5pIWJmzKWZo',
    appId: '1:394923376722:android:e6ed7ade577b4f990a5f8b',
    messagingSenderId: '394923376722',
    projectId: 'fir-authentication-752b6',
    storageBucket: 'fir-authentication-752b6.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDzQjyyRe4LKJGqeR7OBHgXc3uPgWBsxQ',
    appId: '1:394923376722:web:5967517f99b475560a5f8b',
    messagingSenderId: '394923376722',
    projectId: 'fir-authentication-752b6',
    authDomain: 'fir-authentication-752b6.firebaseapp.com',
    storageBucket: 'fir-authentication-752b6.firebasestorage.app',
  );
}
